-- =============================================================================
-- Credit Card Fraud Detection ML Demo - Environment Setup
-- Snowflake ML Capabilities: Feature Store, Experiment Tracking,
--                            Model Registry, Model Serving
-- =============================================================================

-- ===================== ROLE & PRIVILEGES =====================
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS ML_DEMO_ROLE;
GRANT ROLE ML_DEMO_ROLE TO ROLE SYSADMIN;

-- Grant BIND SERVICE ENDPOINT for model serving
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE ML_DEMO_ROLE;

-- ===================== WAREHOUSE =====================
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS ML_DEMO_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for Banking ML Demo';

GRANT USAGE ON WAREHOUSE ML_DEMO_WH TO ROLE ML_DEMO_ROLE;

-- ===================== DATABASE & SCHEMA =====================
CREATE DATABASE IF NOT EXISTS BANKING_ML_DEMO
    COMMENT = 'Database for Credit Card Fraud Detection ML Demo';

USE DATABASE BANKING_ML_DEMO;

CREATE SCHEMA IF NOT EXISTS FRAUD_DETECTION
    COMMENT = 'Schema for fraud detection feature store, models, and experiments';

-- Grant privileges
GRANT ALL ON DATABASE BANKING_ML_DEMO TO ROLE ML_DEMO_ROLE;
GRANT ALL ON SCHEMA BANKING_ML_DEMO.FRAUD_DETECTION TO ROLE ML_DEMO_ROLE;
GRANT CREATE TABLE ON SCHEMA BANKING_ML_DEMO.FRAUD_DETECTION TO ROLE ML_DEMO_ROLE;
GRANT CREATE VIEW ON SCHEMA BANKING_ML_DEMO.FRAUD_DETECTION TO ROLE ML_DEMO_ROLE;
GRANT CREATE DYNAMIC TABLE ON SCHEMA BANKING_ML_DEMO.FRAUD_DETECTION TO ROLE ML_DEMO_ROLE;
GRANT CREATE STAGE ON SCHEMA BANKING_ML_DEMO.FRAUD_DETECTION TO ROLE ML_DEMO_ROLE;
GRANT CREATE SNOWFLAKE.ML.EXPERIMENT ON SCHEMA BANKING_ML_DEMO.FRAUD_DETECTION TO ROLE ML_DEMO_ROLE;

-- ===================== COMPUTE POOL (Model Serving) =====================
USE ROLE ACCOUNTADMIN;

CREATE COMPUTE POOL IF NOT EXISTS ML_DEMO_CPU_POOL
    MIN_NODES = 1
    MAX_NODES = 3
    INSTANCE_FAMILY = CPU_X64_XS
    AUTO_SUSPEND_SECS = 300
    AUTO_RESUME = TRUE
    COMMENT = 'CPU compute pool for fraud detection model serving';

GRANT USAGE ON COMPUTE POOL ML_DEMO_CPU_POOL TO ROLE ML_DEMO_ROLE;

-- ===================== IMAGE REPOSITORY (Model Serving) =====================
USE ROLE SYSADMIN;
USE DATABASE BANKING_ML_DEMO;
USE SCHEMA FRAUD_DETECTION;

CREATE IMAGE REPOSITORY IF NOT EXISTS ML_DEMO_IMAGE_REPO
    COMMENT = 'Image repository for model serving containers';

GRANT READ, WRITE ON IMAGE REPOSITORY ML_DEMO_IMAGE_REPO TO ROLE ML_DEMO_ROLE;

-- ===================== INTERNAL STAGE (Streamlit App) =====================
CREATE OR REPLACE STAGE STREAMLIT_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    COMMENT = 'Stage for Streamlit app files';

GRANT READ, WRITE ON STAGE STREAMLIT_STAGE TO ROLE ML_DEMO_ROLE;

-- ===================== VERIFY SETUP =====================
USE ROLE ML_DEMO_ROLE;
USE WAREHOUSE ML_DEMO_WH;
USE DATABASE BANKING_ML_DEMO;
USE SCHEMA FRAUD_DETECTION;

SELECT CURRENT_ROLE() AS ROLE,
       CURRENT_WAREHOUSE() AS WAREHOUSE,
       CURRENT_DATABASE() AS DATABASE,
       CURRENT_SCHEMA() AS SCHEMA;
